apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-detection
  labels:
    {{- include "viola.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.detection.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "viola.selectorLabels" (dict "component" "detection" "Release" .Release) | nindent 4 }}
