// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: telemetry/envelope.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ObservedAt    string                 `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ReceivedAt    string                 `protobuf:"bytes,4,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	EventType     string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_telemetry_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_telemetry_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EventEnvelope) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EventEnvelope) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *EventEnvelope) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_telemetry_envelope_proto protoreflect.FileDescriptor

const file_telemetry_envelope_proto_rawDesc = "" +
	"\n" +
	"\x18telemetry/envelope.proto\x12\x12viola.telemetry.v1\"\xde\x02\n" +
	"\rEventEnvelope\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1f\n" +
	"\vobserved_at\x18\x03 \x01(\tR\n" +
	"observedAt\x12\x1f\n" +
	"\vreceived_at\x18\x04 \x01(\tR\n" +
	"receivedAt\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12E\n" +
	"\x06labels\x18\b \x03(\v2-.viola.telemetry.v1.EventEnvelope.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xc6\x01\n" +
	"\x16com.viola.telemetry.v1B\rEnvelopeProtoP\x01Z3github.com/viola/shared/proto/telemetry;telemetryv1\xa2\x02\x03VTX\xaa\x02\x12Viola.Telemetry.V1\xca\x02\x12Viola\\Telemetry\\V1\xe2\x02\x1eViola\\Telemetry\\V1\\GPBMetadata\xea\x02\x14Viola::Telemetry::V1b\x06proto3"

var (
	file_telemetry_envelope_proto_rawDescOnce sync.Once
	file_telemetry_envelope_proto_rawDescData []byte
)

func file_telemetry_envelope_proto_rawDescGZIP() []byte {
	file_telemetry_envelope_proto_rawDescOnce.Do(func() {
		file_telemetry_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_envelope_proto_rawDesc), len(file_telemetry_envelope_proto_rawDesc)))
	})
	return file_telemetry_envelope_proto_rawDescData
}

var file_telemetry_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telemetry_envelope_proto_goTypes = []any{
	(*EventEnvelope)(nil), // 0: viola.telemetry.v1.EventEnvelope
	nil,                   // 1: viola.telemetry.v1.EventEnvelope.LabelsEntry
}
var file_telemetry_envelope_proto_depIdxs = []int32{
	1, // 0: viola.telemetry.v1.EventEnvelope.labels:type_name -> viola.telemetry.v1.EventEnvelope.LabelsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_telemetry_envelope_proto_init() }
func file_telemetry_envelope_proto_init() {
	if File_telemetry_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_envelope_proto_rawDesc), len(file_telemetry_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_envelope_proto_goTypes,
		DependencyIndexes: file_telemetry_envelope_proto_depIdxs,
		MessageInfos:      file_telemetry_envelope_proto_msgTypes,
	}.Build()
	File_telemetry_envelope_proto = out.File
	file_telemetry_envelope_proto_goTypes = nil
	file_telemetry_envelope_proto_depIdxs = nil
}
