// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/graph.proto

package graphv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraphEdgeObserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	ObservedAt    string                 `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	SourceNodeId  string                 `protobuf:"bytes,4,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,5,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	EdgeType      string                 `protobuf:"bytes,6,opt,name=edge_type,json=edgeType,proto3" json:"edge_type,omitempty"`
	Weight        float64                `protobuf:"fixed64,7,opt,name=weight,proto3" json:"weight,omitempty"`
	Provenance    string                 `protobuf:"bytes,8,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestId     string                 `protobuf:"bytes,10,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdgeObserved) Reset() {
	*x = GraphEdgeObserved{}
	mi := &file_graph_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdgeObserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdgeObserved) ProtoMessage() {}

func (x *GraphEdgeObserved) ProtoReflect() protoreflect.Message {
	mi := &file_graph_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdgeObserved.ProtoReflect.Descriptor instead.
func (*GraphEdgeObserved) Descriptor() ([]byte, []int) {
	return file_graph_graph_proto_rawDescGZIP(), []int{0}
}

func (x *GraphEdgeObserved) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GraphEdgeObserved) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *GraphEdgeObserved) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *GraphEdgeObserved) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *GraphEdgeObserved) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *GraphEdgeObserved) GetEdgeType() string {
	if x != nil {
		return x.EdgeType
	}
	return ""
}

func (x *GraphEdgeObserved) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *GraphEdgeObserved) GetProvenance() string {
	if x != nil {
		return x.Provenance
	}
	return ""
}

func (x *GraphEdgeObserved) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GraphEdgeObserved) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GraphRiskUpdate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TenantId             string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	NodeId               string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RiskScore            float64                `protobuf:"fixed64,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Reason               string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ContributingEdgeIds  []string               `protobuf:"bytes,6,rep,name=contributing_edge_ids,json=contributingEdgeIds,proto3" json:"contributing_edge_ids,omitempty"`
	ContributingAlertIds []string               `protobuf:"bytes,7,rep,name=contributing_alert_ids,json=contributingAlertIds,proto3" json:"contributing_alert_ids,omitempty"`
	RequestId            string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GraphRiskUpdate) Reset() {
	*x = GraphRiskUpdate{}
	mi := &file_graph_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRiskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRiskUpdate) ProtoMessage() {}

func (x *GraphRiskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_graph_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRiskUpdate.ProtoReflect.Descriptor instead.
func (*GraphRiskUpdate) Descriptor() ([]byte, []int) {
	return file_graph_graph_proto_rawDescGZIP(), []int{1}
}

func (x *GraphRiskUpdate) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GraphRiskUpdate) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GraphRiskUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GraphRiskUpdate) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *GraphRiskUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GraphRiskUpdate) GetContributingEdgeIds() []string {
	if x != nil {
		return x.ContributingEdgeIds
	}
	return nil
}

func (x *GraphRiskUpdate) GetContributingAlertIds() []string {
	if x != nil {
		return x.ContributingAlertIds
	}
	return nil
}

func (x *GraphRiskUpdate) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_graph_graph_proto protoreflect.FileDescriptor

const file_graph_graph_proto_rawDesc = "" +
	"\n" +
	"\x11graph/graph.proto\x12\x0eviola.graph.v1\"\xac\x03\n" +
	"\x11GraphEdgeObserved\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12\x1f\n" +
	"\vobserved_at\x18\x03 \x01(\tR\n" +
	"observedAt\x12$\n" +
	"\x0esource_node_id\x18\x04 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x05 \x01(\tR\ftargetNodeId\x12\x1b\n" +
	"\tedge_type\x18\x06 \x01(\tR\bedgeType\x12\x16\n" +
	"\x06weight\x18\a \x01(\x01R\x06weight\x12\x1e\n" +
	"\n" +
	"provenance\x18\b \x01(\tR\n" +
	"provenance\x12E\n" +
	"\x06labels\x18\t \x03(\v2-.viola.graph.v1.GraphEdgeObserved.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"request_id\x18\n" +
	" \x01(\tR\trequestId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x02\n" +
	"\x0fGraphRiskUpdate\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x01R\triskScore\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x122\n" +
	"\x15contributing_edge_ids\x18\x06 \x03(\tR\x13contributingEdgeIds\x124\n" +
	"\x16contributing_alert_ids\x18\a \x03(\tR\x14contributingAlertIds\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestIdB\xa7\x01\n" +
	"\x12com.viola.graph.v1B\n" +
	"GraphProtoP\x01Z+github.com/viola/shared/proto/graph;graphv1\xa2\x02\x03VGX\xaa\x02\x0eViola.Graph.V1\xca\x02\x0eViola\\Graph\\V1\xe2\x02\x1aViola\\Graph\\V1\\GPBMetadata\xea\x02\x10Viola::Graph::V1b\x06proto3"

var (
	file_graph_graph_proto_rawDescOnce sync.Once
	file_graph_graph_proto_rawDescData []byte
)

func file_graph_graph_proto_rawDescGZIP() []byte {
	file_graph_graph_proto_rawDescOnce.Do(func() {
		file_graph_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_graph_proto_rawDesc), len(file_graph_graph_proto_rawDesc)))
	})
	return file_graph_graph_proto_rawDescData
}

var file_graph_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_graph_graph_proto_goTypes = []any{
	(*GraphEdgeObserved)(nil), // 0: viola.graph.v1.GraphEdgeObserved
	(*GraphRiskUpdate)(nil),   // 1: viola.graph.v1.GraphRiskUpdate
	nil,                       // 2: viola.graph.v1.GraphEdgeObserved.LabelsEntry
}
var file_graph_graph_proto_depIdxs = []int32{
	2, // 0: viola.graph.v1.GraphEdgeObserved.labels:type_name -> viola.graph.v1.GraphEdgeObserved.LabelsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_graph_graph_proto_init() }
func file_graph_graph_proto_init() {
	if File_graph_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_graph_proto_rawDesc), len(file_graph_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_graph_proto_goTypes,
		DependencyIndexes: file_graph_graph_proto_depIdxs,
		MessageInfos:      file_graph_graph_proto_msgTypes,
	}.Build()
	File_graph_graph_proto = out.File
	file_graph_graph_proto_goTypes = nil
	file_graph_graph_proto_depIdxs = nil
}
