apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-viola-config
  labels:
    {{- include "viola.labels" . | nindent 4 }}
data:
  VIOLA_ENV: {{ .Values.global.env | quote }}
  KAFKA_BROKER: {{ .Values.global.kafka.brokers | quote }}
  PG_HOST: {{ .Values.global.postgres.host | quote }}
  PG_PORT: {{ .Values.global.postgres.port | quote }}
  PG_USER: {{ .Values.global.postgres.user | quote }}
  PG_DATABASE: {{ .Values.global.postgres.database | quote }}
  PG_SSLMODE: {{ .Values.global.postgres.sslmode | quote }}
