apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    {{- include "viola.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.auth.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "viola.selectorLabels" (dict "component" "auth" "Release" .Release) | nindent 4 }}
