// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: security/alert.proto

package securityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Alert struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AlertId           string                 `protobuf:"bytes,2,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Severity          string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Confidence        float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RiskScore         float64                `protobuf:"fixed64,8,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Title             string                 `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	EntityIds         []string               `protobuf:"bytes,11,rep,name=entity_ids,json=entityIds,proto3" json:"entity_ids,omitempty"`
	DetectionHitIds   []string               `protobuf:"bytes,12,rep,name=detection_hit_ids,json=detectionHitIds,proto3" json:"detection_hit_ids,omitempty"`
	MitreTactic       string                 `protobuf:"bytes,13,opt,name=mitre_tactic,json=mitreTactic,proto3" json:"mitre_tactic,omitempty"`
	MitreTechnique    string                 `protobuf:"bytes,14,opt,name=mitre_technique,json=mitreTechnique,proto3" json:"mitre_technique,omitempty"`
	Labels            map[string]string      `protobuf:"bytes,15,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AssignedTo        string                 `protobuf:"bytes,16,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	ClosureReason     string                 `protobuf:"bytes,17,opt,name=closure_reason,json=closureReason,proto3" json:"closure_reason,omitempty"`
	RequestId         string                 `protobuf:"bytes,18,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CorrelatedGroupId string                 `protobuf:"bytes,19,opt,name=correlated_group_id,json=correlatedGroupId,proto3" json:"correlated_group_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_security_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_security_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_security_alert_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Alert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Alert) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Alert) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Alert) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Alert) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *Alert) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Alert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alert) GetEntityIds() []string {
	if x != nil {
		return x.EntityIds
	}
	return nil
}

func (x *Alert) GetDetectionHitIds() []string {
	if x != nil {
		return x.DetectionHitIds
	}
	return nil
}

func (x *Alert) GetMitreTactic() string {
	if x != nil {
		return x.MitreTactic
	}
	return ""
}

func (x *Alert) GetMitreTechnique() string {
	if x != nil {
		return x.MitreTechnique
	}
	return ""
}

func (x *Alert) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Alert) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *Alert) GetClosureReason() string {
	if x != nil {
		return x.ClosureReason
	}
	return ""
}

func (x *Alert) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Alert) GetCorrelatedGroupId() string {
	if x != nil {
		return x.CorrelatedGroupId
	}
	return ""
}

var File_security_alert_proto protoreflect.FileDescriptor

const file_security_alert_proto_rawDesc = "" +
	"\n" +
	"\x14security/alert.proto\x12\x11viola.security.v1\"\xcf\x05\n" +
	"\x05Alert\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\balert_id\x18\x02 \x01(\tR\aalertId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"risk_score\x18\b \x01(\x01R\triskScore\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"entity_ids\x18\v \x03(\tR\tentityIds\x12*\n" +
	"\x11detection_hit_ids\x18\f \x03(\tR\x0fdetectionHitIds\x12!\n" +
	"\fmitre_tactic\x18\r \x01(\tR\vmitreTactic\x12'\n" +
	"\x0fmitre_technique\x18\x0e \x01(\tR\x0emitreTechnique\x12<\n" +
	"\x06labels\x18\x0f \x03(\v2$.viola.security.v1.Alert.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vassigned_to\x18\x10 \x01(\tR\n" +
	"assignedTo\x12%\n" +
	"\x0eclosure_reason\x18\x11 \x01(\tR\rclosureReason\x12\x1d\n" +
	"\n" +
	"request_id\x18\x12 \x01(\tR\trequestId\x12.\n" +
	"\x13correlated_group_id\x18\x13 \x01(\tR\x11correlatedGroupId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xbc\x01\n" +
	"\x15com.viola.security.v1B\n" +
	"AlertProtoP\x01Z1github.com/viola/shared/proto/security;securityv1\xa2\x02\x03VSX\xaa\x02\x11Viola.Security.V1\xca\x02\x11Viola\\Security\\V1\xe2\x02\x1dViola\\Security\\V1\\GPBMetadata\xea\x02\x13Viola::Security::V1b\x06proto3"

var (
	file_security_alert_proto_rawDescOnce sync.Once
	file_security_alert_proto_rawDescData []byte
)

func file_security_alert_proto_rawDescGZIP() []byte {
	file_security_alert_proto_rawDescOnce.Do(func() {
		file_security_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_alert_proto_rawDesc), len(file_security_alert_proto_rawDesc)))
	})
	return file_security_alert_proto_rawDescData
}

var file_security_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_security_alert_proto_goTypes = []any{
	(*Alert)(nil), // 0: viola.security.v1.Alert
	nil,           // 1: viola.security.v1.Alert.LabelsEntry
}
var file_security_alert_proto_depIdxs = []int32{
	1, // 0: viola.security.v1.Alert.labels:type_name -> viola.security.v1.Alert.LabelsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_security_alert_proto_init() }
func file_security_alert_proto_init() {
	if File_security_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_alert_proto_rawDesc), len(file_security_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_security_alert_proto_goTypes,
		DependencyIndexes: file_security_alert_proto_depIdxs,
		MessageInfos:      file_security_alert_proto_msgTypes,
	}.Build()
	File_security_alert_proto = out.File
	file_security_alert_proto_goTypes = nil
	file_security_alert_proto_depIdxs = nil
}
