// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: security/detection.proto

package securityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectionHit struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	HitId             string                 `protobuf:"bytes,2,opt,name=hit_id,json=hitId,proto3" json:"hit_id,omitempty"`
	DetectedAt        string                 `protobuf:"bytes,3,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	RuleId            string                 `protobuf:"bytes,4,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName          string                 `protobuf:"bytes,5,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	RuleVersion       string                 `protobuf:"bytes,6,opt,name=rule_version,json=ruleVersion,proto3" json:"rule_version,omitempty"`
	Category          string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Severity          string                 `protobuf:"bytes,8,opt,name=severity,proto3" json:"severity,omitempty"`
	Confidence        float64                `protobuf:"fixed64,9,opt,name=confidence,proto3" json:"confidence,omitempty"`
	EntityIds         []string               `protobuf:"bytes,10,rep,name=entity_ids,json=entityIds,proto3" json:"entity_ids,omitempty"`
	Evidence          []*Evidence            `protobuf:"bytes,11,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Tags              []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	MitreTactic       string                 `protobuf:"bytes,13,opt,name=mitre_tactic,json=mitreTactic,proto3" json:"mitre_tactic,omitempty"`
	MitreTechnique    string                 `protobuf:"bytes,14,opt,name=mitre_technique,json=mitreTechnique,proto3" json:"mitre_technique,omitempty"`
	CorrelatedGroupId string                 `protobuf:"bytes,15,opt,name=correlated_group_id,json=correlatedGroupId,proto3" json:"correlated_group_id,omitempty"`
	RequestId         string                 `protobuf:"bytes,16,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Source            string                 `protobuf:"bytes,17,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DetectionHit) Reset() {
	*x = DetectionHit{}
	mi := &file_security_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionHit) ProtoMessage() {}

func (x *DetectionHit) ProtoReflect() protoreflect.Message {
	mi := &file_security_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionHit.ProtoReflect.Descriptor instead.
func (*DetectionHit) Descriptor() ([]byte, []int) {
	return file_security_detection_proto_rawDescGZIP(), []int{0}
}

func (x *DetectionHit) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DetectionHit) GetHitId() string {
	if x != nil {
		return x.HitId
	}
	return ""
}

func (x *DetectionHit) GetDetectedAt() string {
	if x != nil {
		return x.DetectedAt
	}
	return ""
}

func (x *DetectionHit) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *DetectionHit) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *DetectionHit) GetRuleVersion() string {
	if x != nil {
		return x.RuleVersion
	}
	return ""
}

func (x *DetectionHit) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DetectionHit) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *DetectionHit) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectionHit) GetEntityIds() []string {
	if x != nil {
		return x.EntityIds
	}
	return nil
}

func (x *DetectionHit) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *DetectionHit) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DetectionHit) GetMitreTactic() string {
	if x != nil {
		return x.MitreTactic
	}
	return ""
}

func (x *DetectionHit) GetMitreTechnique() string {
	if x != nil {
		return x.MitreTechnique
	}
	return ""
}

func (x *DetectionHit) GetCorrelatedGroupId() string {
	if x != nil {
		return x.CorrelatedGroupId
	}
	return ""
}

func (x *DetectionHit) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DetectionHit) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Evidence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ObservedAt     string                 `protobuf:"bytes,1,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	EventType      string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EntityId       string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Summary        string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	PayloadSnippet []byte                 `protobuf:"bytes,5,opt,name=payload_snippet,json=payloadSnippet,proto3" json:"payload_snippet,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_security_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_security_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_security_detection_proto_rawDescGZIP(), []int{1}
}

func (x *Evidence) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *Evidence) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Evidence) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Evidence) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Evidence) GetPayloadSnippet() []byte {
	if x != nil {
		return x.PayloadSnippet
	}
	return nil
}

func (x *Evidence) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_security_detection_proto protoreflect.FileDescriptor

const file_security_detection_proto_rawDesc = "" +
	"\n" +
	"\x18security/detection.proto\x12\x11viola.security.v1\"\xb3\x04\n" +
	"\fDetectionHit\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06hit_id\x18\x02 \x01(\tR\x05hitId\x12\x1f\n" +
	"\vdetected_at\x18\x03 \x01(\tR\n" +
	"detectedAt\x12\x17\n" +
	"\arule_id\x18\x04 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x05 \x01(\tR\bruleName\x12!\n" +
	"\frule_version\x18\x06 \x01(\tR\vruleVersion\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\b \x01(\tR\bseverity\x12\x1e\n" +
	"\n" +
	"confidence\x18\t \x01(\x01R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"entity_ids\x18\n" +
	" \x03(\tR\tentityIds\x127\n" +
	"\bevidence\x18\v \x03(\v2\x1b.viola.security.v1.EvidenceR\bevidence\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12!\n" +
	"\fmitre_tactic\x18\r \x01(\tR\vmitreTactic\x12'\n" +
	"\x0fmitre_technique\x18\x0e \x01(\tR\x0emitreTechnique\x12.\n" +
	"\x13correlated_group_id\x18\x0f \x01(\tR\x11correlatedGroupId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x10 \x01(\tR\trequestId\x12\x16\n" +
	"\x06source\x18\x11 \x01(\tR\x06source\"\xa6\x02\n" +
	"\bEvidence\x12\x1f\n" +
	"\vobserved_at\x18\x01 \x01(\tR\n" +
	"observedAt\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12'\n" +
	"\x0fpayload_snippet\x18\x05 \x01(\fR\x0epayloadSnippet\x12?\n" +
	"\x06labels\x18\x06 \x03(\v2'.viola.security.v1.Evidence.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xc0\x01\n" +
	"\x15com.viola.security.v1B\x0eDetectionProtoP\x01Z1github.com/viola/shared/proto/security;securityv1\xa2\x02\x03VSX\xaa\x02\x11Viola.Security.V1\xca\x02\x11Viola\\Security\\V1\xe2\x02\x1dViola\\Security\\V1\\GPBMetadata\xea\x02\x13Viola::Security::V1b\x06proto3"

var (
	file_security_detection_proto_rawDescOnce sync.Once
	file_security_detection_proto_rawDescData []byte
)

func file_security_detection_proto_rawDescGZIP() []byte {
	file_security_detection_proto_rawDescOnce.Do(func() {
		file_security_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_detection_proto_rawDesc), len(file_security_detection_proto_rawDesc)))
	})
	return file_security_detection_proto_rawDescData
}

var file_security_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_security_detection_proto_goTypes = []any{
	(*DetectionHit)(nil), // 0: viola.security.v1.DetectionHit
	(*Evidence)(nil),     // 1: viola.security.v1.Evidence
	nil,                  // 2: viola.security.v1.Evidence.LabelsEntry
}
var file_security_detection_proto_depIdxs = []int32{
	1, // 0: viola.security.v1.DetectionHit.evidence:type_name -> viola.security.v1.Evidence
	2, // 1: viola.security.v1.Evidence.labels:type_name -> viola.security.v1.Evidence.LabelsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_security_detection_proto_init() }
func file_security_detection_proto_init() {
	if File_security_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_detection_proto_rawDesc), len(file_security_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_security_detection_proto_goTypes,
		DependencyIndexes: file_security_detection_proto_depIdxs,
		MessageInfos:      file_security_detection_proto_msgTypes,
	}.Build()
	File_security_detection_proto = out.File
	file_security_detection_proto_goTypes = nil
	file_security_detection_proto_depIdxs = nil
}
