// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: response/response.proto

package responsev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ResponseId       string                 `protobuf:"bytes,2,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	RequestedAt      string                 `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	RequestedBy      string                 `protobuf:"bytes,4,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	ActionType       string                 `protobuf:"bytes,5,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	TargetType       string                 `protobuf:"bytes,6,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId         string                 `protobuf:"bytes,7,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Reason           string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	Confidence       float64                `protobuf:"fixed64,9,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RequiresApproval bool                   `protobuf:"varint,10,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	ApprovalId       string                 `protobuf:"bytes,11,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	RelatedAlertIds  []string               `protobuf:"bytes,12,rep,name=related_alert_ids,json=relatedAlertIds,proto3" json:"related_alert_ids,omitempty"`
	Parameters       map[string]string      `protobuf:"bytes,13,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestId        string                 `protobuf:"bytes,14,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResponseRequest) Reset() {
	*x = ResponseRequest{}
	mi := &file_response_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRequest) ProtoMessage() {}

func (x *ResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRequest.ProtoReflect.Descriptor instead.
func (*ResponseRequest) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResponseRequest) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *ResponseRequest) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

func (x *ResponseRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *ResponseRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ResponseRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ResponseRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ResponseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResponseRequest) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ResponseRequest) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *ResponseRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ResponseRequest) GetRelatedAlertIds() []string {
	if x != nil {
		return x.RelatedAlertIds
	}
	return nil
}

func (x *ResponseRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ResponseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ResponseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ResponseId    string                 `protobuf:"bytes,2,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	ExecutedAt    string                 `protobuf:"bytes,3,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	ActionType    string                 `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	TargetType    string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Outcome       string                 `protobuf:"bytes,7,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Details       string                 `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
	Artifacts     map[string]string      `protobuf:"bytes,9,rep,name=artifacts,proto3" json:"artifacts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestId     string                 `protobuf:"bytes,10,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseResult) Reset() {
	*x = ResponseResult{}
	mi := &file_response_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseResult) ProtoMessage() {}

func (x *ResponseResult) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseResult.ProtoReflect.Descriptor instead.
func (*ResponseResult) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseResult) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResponseResult) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *ResponseResult) GetExecutedAt() string {
	if x != nil {
		return x.ExecutedAt
	}
	return ""
}

func (x *ResponseResult) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ResponseResult) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ResponseResult) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ResponseResult) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ResponseResult) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *ResponseResult) GetArtifacts() map[string]string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ResponseResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ResponseFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ResponseId    string                 `protobuf:"bytes,2,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	FailedAt      string                 `protobuf:"bytes,3,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	ActionType    string                 `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	TargetType    string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Retryable     bool                   `protobuf:"varint,9,opt,name=retryable,proto3" json:"retryable,omitempty"`
	RetryAfter    string                 `protobuf:"bytes,10,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	RequestId     string                 `protobuf:"bytes,11,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFailure) Reset() {
	*x = ResponseFailure{}
	mi := &file_response_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFailure) ProtoMessage() {}

func (x *ResponseFailure) ProtoReflect() protoreflect.Message {
	mi := &file_response_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFailure.ProtoReflect.Descriptor instead.
func (*ResponseFailure) Descriptor() ([]byte, []int) {
	return file_response_response_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseFailure) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResponseFailure) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *ResponseFailure) GetFailedAt() string {
	if x != nil {
		return x.FailedAt
	}
	return ""
}

func (x *ResponseFailure) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ResponseFailure) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ResponseFailure) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ResponseFailure) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ResponseFailure) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ResponseFailure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ResponseFailure) GetRetryAfter() string {
	if x != nil {
		return x.RetryAfter
	}
	return ""
}

func (x *ResponseFailure) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_response_response_proto protoreflect.FileDescriptor

const file_response_response_proto_rawDesc = "" +
	"\n" +
	"\x17response/response.proto\x12\x11viola.response.v1\"\xd8\x04\n" +
	"\x0fResponseRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vresponse_id\x18\x02 \x01(\tR\n" +
	"responseId\x12!\n" +
	"\frequested_at\x18\x03 \x01(\tR\vrequestedAt\x12!\n" +
	"\frequested_by\x18\x04 \x01(\tR\vrequestedBy\x12\x1f\n" +
	"\vaction_type\x18\x05 \x01(\tR\n" +
	"actionType\x12\x1f\n" +
	"\vtarget_type\x18\x06 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\a \x01(\tR\btargetId\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"confidence\x18\t \x01(\x01R\n" +
	"confidence\x12+\n" +
	"\x11requires_approval\x18\n" +
	" \x01(\bR\x10requiresApproval\x12\x1f\n" +
	"\vapproval_id\x18\v \x01(\tR\n" +
	"approvalId\x12*\n" +
	"\x11related_alert_ids\x18\f \x03(\tR\x0frelatedAlertIds\x12R\n" +
	"\n" +
	"parameters\x18\r \x03(\v22.viola.response.v1.ResponseRequest.ParametersEntryR\n" +
	"parameters\x12\x1d\n" +
	"\n" +
	"request_id\x18\x0e \x01(\tR\trequestId\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x03\n" +
	"\x0eResponseResult\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vresponse_id\x18\x02 \x01(\tR\n" +
	"responseId\x12\x1f\n" +
	"\vexecuted_at\x18\x03 \x01(\tR\n" +
	"executedAt\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x12\x18\n" +
	"\aoutcome\x18\a \x01(\tR\aoutcome\x12\x18\n" +
	"\adetails\x18\b \x01(\tR\adetails\x12N\n" +
	"\tartifacts\x18\t \x03(\v20.viola.response.v1.ResponseResult.ArtifactsEntryR\tartifacts\x12\x1d\n" +
	"\n" +
	"request_id\x18\n" +
	" \x01(\tR\trequestId\x1a<\n" +
	"\x0eArtifactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\x02\n" +
	"\x0fResponseFailure\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vresponse_id\x18\x02 \x01(\tR\n" +
	"responseId\x12\x1b\n" +
	"\tfailed_at\x18\x03 \x01(\tR\bfailedAt\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x12\x1d\n" +
	"\n" +
	"error_code\x18\a \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\tretryable\x18\t \x01(\bR\tretryable\x12\x1f\n" +
	"\vretry_after\x18\n" +
	" \x01(\tR\n" +
	"retryAfter\x12\x1d\n" +
	"\n" +
	"request_id\x18\v \x01(\tR\trequestIdB\xbf\x01\n" +
	"\x15com.viola.response.v1B\rResponseProtoP\x01Z1github.com/viola/shared/proto/response;responsev1\xa2\x02\x03VRX\xaa\x02\x11Viola.Response.V1\xca\x02\x11Viola\\Response\\V1\xe2\x02\x1dViola\\Response\\V1\\GPBMetadata\xea\x02\x13Viola::Response::V1b\x06proto3"

var (
	file_response_response_proto_rawDescOnce sync.Once
	file_response_response_proto_rawDescData []byte
)

func file_response_response_proto_rawDescGZIP() []byte {
	file_response_response_proto_rawDescOnce.Do(func() {
		file_response_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_response_proto_rawDesc), len(file_response_response_proto_rawDesc)))
	})
	return file_response_response_proto_rawDescData
}

var file_response_response_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_response_response_proto_goTypes = []any{
	(*ResponseRequest)(nil), // 0: viola.response.v1.ResponseRequest
	(*ResponseResult)(nil),  // 1: viola.response.v1.ResponseResult
	(*ResponseFailure)(nil), // 2: viola.response.v1.ResponseFailure
	nil,                     // 3: viola.response.v1.ResponseRequest.ParametersEntry
	nil,                     // 4: viola.response.v1.ResponseResult.ArtifactsEntry
}
var file_response_response_proto_depIdxs = []int32{
	3, // 0: viola.response.v1.ResponseRequest.parameters:type_name -> viola.response.v1.ResponseRequest.ParametersEntry
	4, // 1: viola.response.v1.ResponseResult.artifacts:type_name -> viola.response.v1.ResponseResult.ArtifactsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_response_response_proto_init() }
func file_response_response_proto_init() {
	if File_response_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_response_proto_rawDesc), len(file_response_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_response_proto_goTypes,
		DependencyIndexes: file_response_response_proto_depIdxs,
		MessageInfos:      file_response_response_proto_msgTypes,
	}.Build()
	File_response_response_proto = out.File
	file_response_response_proto_goTypes = nil
	file_response_response_proto_depIdxs = nil
}
