{{- if (index .Values "gateway-api").autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-gateway-api
  labels:
    {{- include "viola.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-gateway-api
  minReplicas: {{ (index .Values "gateway-api").autoscaling.minReplicas }}
  maxReplicas: {{ (index .Values "gateway-api").autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ (index .Values "gateway-api").autoscaling.targetCPU }}
{{- end }}
