import type {
  ComplianceControl,
  ComplianceScore,
  AuditEvent,
} from "@/types/compliance";

export const MOCK_COMPLIANCE_SCORES: ComplianceScore[] = [
  {
    framework: "soc2",
    overall_score: 87,
    passing: 42,
    failing: 3,
    partial: 6,
    not_assessed: 2,
    total: 53,
    last_updated: "2024-11-15T10:00:00Z",
  },
  {
    framework: "hipaa",
    overall_score: 74,
    passing: 28,
    failing: 5,
    partial: 8,
    not_assessed: 4,
    total: 45,
    last_updated: "2024-11-14T18:30:00Z",
  },
  {
    framework: "nist-csf",
    overall_score: 81,
    passing: 35,
    failing: 4,
    partial: 5,
    not_assessed: 3,
    total: 47,
    last_updated: "2024-11-15T06:00:00Z",
  },
  {
    framework: "pci-dss",
    overall_score: 69,
    passing: 22,
    failing: 6,
    partial: 7,
    not_assessed: 5,
    total: 40,
    last_updated: "2024-11-13T12:00:00Z",
  },
];

export const MOCK_CONTROLS: ComplianceControl[] = [
  // SOC 2
  {
    control_id: "CC1.1",
    framework: "soc2",
    category: "Control Environment",
    title: "COSO Principle 1 — Integrity and Ethical Values",
    description:
      "The entity demonstrates a commitment to integrity and ethical values.",
    status: "passing",
    evidence_count: 4,
    last_assessed: "2024-11-10T08:00:00Z",
    owner: "compliance@viola.corp",
    notes: null,
  },
  {
    control_id: "CC2.1",
    framework: "soc2",
    category: "Communication and Information",
    title: "Internal Communication of Objectives",
    description:
      "The entity internally communicates information necessary to support the functioning of internal control.",
    status: "passing",
    evidence_count: 3,
    last_assessed: "2024-11-10T08:00:00Z",
    owner: "compliance@viola.corp",
    notes: null,
  },
  {
    control_id: "CC6.1",
    framework: "soc2",
    category: "Logical and Physical Access Controls",
    title: "Logical Access Security",
    description:
      "The entity implements logical access security software, infrastructure, and architectures over protected information assets.",
    status: "passing",
    evidence_count: 8,
    last_assessed: "2024-11-12T14:00:00Z",
    owner: "security@viola.corp",
    notes: null,
  },
  {
    control_id: "CC6.3",
    framework: "soc2",
    category: "Logical and Physical Access Controls",
    title: "Role-Based Access and Least Privilege",
    description:
      "The entity authorizes, modifies, or removes access based on roles, responsibilities, or the system design.",
    status: "partial",
    evidence_count: 5,
    last_assessed: "2024-11-13T10:00:00Z",
    owner: "security@viola.corp",
    notes: "Service account permissions need review for 3 microservices.",
  },
  {
    control_id: "CC7.2",
    framework: "soc2",
    category: "System Operations",
    title: "Monitoring System Components",
    description:
      "The entity monitors system components and the operation of those components for anomalies.",
    status: "passing",
    evidence_count: 12,
    last_assessed: "2024-11-14T16:00:00Z",
    owner: "sre@viola.corp",
    notes: null,
  },
  {
    control_id: "CC8.1",
    framework: "soc2",
    category: "Change Management",
    title: "Changes to Infrastructure and Software",
    description:
      "The entity authorizes, designs, develops or acquires, configures, documents, tests, approves, and implements changes.",
    status: "passing",
    evidence_count: 6,
    last_assessed: "2024-11-12T09:00:00Z",
    owner: "engineering@viola.corp",
    notes: null,
  },
  {
    control_id: "CC9.1",
    framework: "soc2",
    category: "Risk Mitigation",
    title: "Risk Mitigation Activities",
    description: "The entity identifies, selects, and develops risk mitigation activities.",
    status: "failing",
    evidence_count: 1,
    last_assessed: "2024-11-08T11:00:00Z",
    owner: "compliance@viola.corp",
    notes: "Formal risk assessment not completed for Q4. Due by Nov 30.",
  },
  // HIPAA
  {
    control_id: "164.312(a)(1)",
    framework: "hipaa",
    category: "Access Control",
    title: "Unique User Identification",
    description: "Assign a unique name and/or number for identifying and tracking user identity.",
    status: "passing",
    evidence_count: 3,
    last_assessed: "2024-11-10T08:00:00Z",
    owner: "security@viola.corp",
    notes: null,
  },
  {
    control_id: "164.312(a)(2)(iv)",
    framework: "hipaa",
    category: "Access Control",
    title: "Encryption and Decryption",
    description: "Implement a mechanism to encrypt and decrypt electronic protected health information.",
    status: "passing",
    evidence_count: 5,
    last_assessed: "2024-11-11T10:00:00Z",
    owner: "security@viola.corp",
    notes: null,
  },
  {
    control_id: "164.312(b)",
    framework: "hipaa",
    category: "Audit Controls",
    title: "Audit Controls",
    description:
      "Implement hardware, software, and/or procedural mechanisms that record and examine activity.",
    status: "partial",
    evidence_count: 4,
    last_assessed: "2024-11-13T14:00:00Z",
    owner: "sre@viola.corp",
    notes: "Audit log retention needs extension from 30 to 90 days.",
  },
  {
    control_id: "164.312(c)(1)",
    framework: "hipaa",
    category: "Integrity",
    title: "Integrity Controls",
    description:
      "Implement policies and procedures to protect ePHI from improper alteration or destruction.",
    status: "failing",
    evidence_count: 1,
    last_assessed: "2024-11-09T08:00:00Z",
    owner: "security@viola.corp",
    notes: "Need checksums on PHI data at rest. Remediation planned.",
  },
  // NIST CSF
  {
    control_id: "ID.AM-1",
    framework: "nist-csf",
    category: "Identify — Asset Management",
    title: "Physical Devices and Systems Inventory",
    description: "Physical devices and systems within the organization are inventoried.",
    status: "passing",
    evidence_count: 6,
    last_assessed: "2024-11-12T08:00:00Z",
    owner: "it-ops@viola.corp",
    notes: null,
  },
  {
    control_id: "PR.AC-1",
    framework: "nist-csf",
    category: "Protect — Access Control",
    title: "Identities and Credentials Management",
    description: "Identities and credentials are issued, managed, verified, revoked, and audited.",
    status: "passing",
    evidence_count: 7,
    last_assessed: "2024-11-14T10:00:00Z",
    owner: "security@viola.corp",
    notes: null,
  },
  {
    control_id: "DE.CM-1",
    framework: "nist-csf",
    category: "Detect — Continuous Monitoring",
    title: "Network Monitoring",
    description: "The network is monitored to detect potential cybersecurity events.",
    status: "passing",
    evidence_count: 15,
    last_assessed: "2024-11-15T06:00:00Z",
    owner: "soc@viola.corp",
    notes: null,
  },
  {
    control_id: "RS.RP-1",
    framework: "nist-csf",
    category: "Respond — Response Planning",
    title: "Response Plan Execution",
    description: "Response plan is executed during or after an incident.",
    status: "partial",
    evidence_count: 3,
    last_assessed: "2024-11-11T12:00:00Z",
    owner: "soc@viola.corp",
    notes: "Playbooks exist but need tabletop exercise validation.",
  },
];

export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    event_id: "aud-001",
    timestamp: "2024-11-15T09:45:00Z",
    actor: "system",
    action: "automated_scan",
    resource: "CC7.2 — Monitoring System Components",
    framework: "soc2",
    control_id: "CC7.2",
    result: "pass",
  },
  {
    event_id: "aud-002",
    timestamp: "2024-11-15T09:30:00Z",
    actor: "compliance@viola.corp",
    action: "evidence_uploaded",
    resource: "CC6.1 — Logical Access Security",
    framework: "soc2",
    control_id: "CC6.1",
    result: "info",
  },
  {
    event_id: "aud-003",
    timestamp: "2024-11-15T08:15:00Z",
    actor: "system",
    action: "control_check",
    resource: "164.312(c)(1) — Integrity Controls",
    framework: "hipaa",
    control_id: "164.312(c)(1)",
    result: "fail",
  },
  {
    event_id: "aud-004",
    timestamp: "2024-11-15T07:00:00Z",
    actor: "security@viola.corp",
    action: "manual_review",
    resource: "PR.AC-1 — Identities and Credentials Management",
    framework: "nist-csf",
    control_id: "PR.AC-1",
    result: "pass",
  },
  {
    event_id: "aud-005",
    timestamp: "2024-11-14T22:00:00Z",
    actor: "system",
    action: "automated_scan",
    resource: "CC9.1 — Risk Mitigation Activities",
    framework: "soc2",
    control_id: "CC9.1",
    result: "fail",
  },
  {
    event_id: "aud-006",
    timestamp: "2024-11-14T16:30:00Z",
    actor: "sre@viola.corp",
    action: "evidence_uploaded",
    resource: "DE.CM-1 — Network Monitoring",
    framework: "nist-csf",
    control_id: "DE.CM-1",
    result: "info",
  },
];
