import type { GraphNode, GraphEdge, AttackGraph } from "@/types/graph";

const MOCK_NODES: GraphNode[] = [
  {
    id: "workstation-42",
    label: "workstation-42.corp",
    type: "device",
    risk_score: 94,
    entity_ids: ["host:workstation-42.corp"],
    is_crown_jewel: false,
    metadata: { os: "Windows 11", department: "Engineering" },
  },
  {
    id: "dc01",
    label: "dc01.corp",
    type: "service",
    risk_score: 88,
    entity_ids: ["host:dc01.corp"],
    is_crown_jewel: true,
    metadata: { role: "Domain Controller", os: "Windows Server 2022" },
  },
  {
    id: "fileserver-03",
    label: "fileserver-03.corp",
    type: "service",
    risk_score: 98,
    entity_ids: ["host:fileserver-03.corp"],
    is_crown_jewel: true,
    metadata: { role: "File Server", os: "Windows Server 2022" },
  },
  {
    id: "laptop-07",
    label: "laptop-07.corp",
    type: "device",
    risk_score: 73,
    entity_ids: ["host:laptop-07.corp"],
    is_crown_jewel: false,
    metadata: { os: "macOS 14", department: "Sales" },
  },
  {
    id: "proxy-01",
    label: "proxy-01.corp",
    type: "service",
    risk_score: 42,
    entity_ids: ["host:proxy-01.corp"],
    is_crown_jewel: false,
    metadata: { role: "Web Proxy", os: "Ubuntu 22.04" },
  },
  {
    id: "server-12",
    label: "server-12.corp",
    type: "service",
    risk_score: 52,
    entity_ids: ["host:server-12.corp"],
    is_crown_jewel: false,
    metadata: { role: "App Server", os: "Ubuntu 22.04" },
  },
  {
    id: "user-analyst",
    label: "analyst@viola.corp",
    type: "user",
    risk_score: 15,
    entity_ids: ["user:analyst@viola.corp"],
    is_crown_jewel: false,
    metadata: { role: "SOC Analyst", department: "Security" },
  },
  {
    id: "user-admin",
    label: "admin@viola.corp",
    type: "user",
    risk_score: 35,
    entity_ids: ["user:admin@viola.corp"],
    is_crown_jewel: false,
    metadata: { role: "Domain Admin", department: "IT" },
  },
  {
    id: "dev-laptop-22",
    label: "dev-laptop-22.corp",
    type: "device",
    risk_score: 18,
    entity_ids: ["host:dev-laptop-22.corp"],
    is_crown_jewel: false,
    metadata: { os: "macOS 14", department: "Engineering" },
  },
  {
    id: "aws-iam-admin",
    label: "arn:aws:iam::123:role/admin",
    type: "cloud-resource",
    risk_score: 65,
    entity_ids: ["arn:aws:iam::123:role/admin"],
    is_crown_jewel: true,
    metadata: { provider: "aws", service: "IAM" },
  },
  {
    id: "aws-s3-data",
    label: "s3://viola-prod-data",
    type: "cloud-resource",
    risk_score: 45,
    entity_ids: ["arn:aws:s3:::viola-prod-data"],
    is_crown_jewel: true,
    metadata: { provider: "aws", service: "S3" },
  },
];

const MOCK_EDGES: GraphEdge[] = [
  {
    id: "e1",
    source: "workstation-42",
    target: "dc01",
    type: "lateral-movement",
    weight: 0.95,
    last_seen: "2024-11-15T08:23:11Z",
    event_count: 14,
    labels: { technique: "pass-the-hash", protocol: "ntlm" },
  },
  {
    id: "e2",
    source: "workstation-42",
    target: "fileserver-03",
    type: "lateral-movement",
    weight: 0.92,
    last_seen: "2024-11-15T09:12:08Z",
    event_count: 8,
    labels: { technique: "smb-spread", protocol: "smb" },
  },
  {
    id: "e3",
    source: "laptop-07",
    target: "proxy-01",
    type: "network",
    weight: 0.81,
    last_seen: "2024-11-15T07:12:45Z",
    event_count: 482,
    labels: { technique: "dns-tunneling", protocol: "dns" },
  },
  {
    id: "e4",
    source: "user-admin",
    target: "dc01",
    type: "auth",
    weight: 0.7,
    last_seen: "2024-11-15T06:00:00Z",
    event_count: 35,
    labels: { method: "kerberos" },
  },
  {
    id: "e5",
    source: "user-admin",
    target: "aws-iam-admin",
    type: "cloud-api",
    weight: 0.6,
    last_seen: "2024-11-14T22:15:00Z",
    event_count: 12,
    labels: { action: "AssumeRole" },
  },
  {
    id: "e6",
    source: "aws-iam-admin",
    target: "aws-s3-data",
    type: "cloud-api",
    weight: 0.5,
    last_seen: "2024-11-14T23:00:00Z",
    event_count: 4,
    labels: { action: "GetObject" },
  },
  {
    id: "e7",
    source: "user-analyst",
    target: "workstation-42",
    type: "auth",
    weight: 0.3,
    last_seen: "2024-11-15T08:00:00Z",
    event_count: 5,
    labels: { method: "rdp" },
  },
  {
    id: "e8",
    source: "server-12",
    target: "proxy-01",
    type: "network",
    weight: 0.4,
    last_seen: "2024-11-14T20:00:00Z",
    event_count: 120,
    labels: { protocol: "https" },
  },
  {
    id: "e9",
    source: "dev-laptop-22",
    target: "server-12",
    type: "network",
    weight: 0.2,
    last_seen: "2024-11-12T16:00:00Z",
    event_count: 15,
    labels: { protocol: "ssh" },
  },
];

export const MOCK_ATTACK_GRAPH: AttackGraph = {
  nodes: MOCK_NODES,
  edges: MOCK_EDGES,
  updated_at: "2024-11-15T10:00:00Z",
};
