import type { Incident, Alert } from "@/types/api";

export const MOCK_INCIDENTS: Incident[] = [
  {
    tenant_id: "dev-tenant",
    incident_id: "INC-2024-001",
    correlated_group_id: "grp-001",
    severity: "critical",
    status: "open",
    max_risk_score: 94,
    max_confidence: 0.91,
    mitre_tactic: "Lateral Movement",
    mitre_technique: "T1021",
    alert_count: 7,
    hit_count: 14,
    assigned_to: null,
    closure_reason: null,
    request_id: null,
    labels: { category: "ransomware", phase: "lateral-movement" },
    entity_ids: ["host:workstation-42.corp", "host:dc01.corp", "host:fileserver-03.corp"],
    alert_ids: ["ALT-2024-00101", "ALT-2024-00102", "ALT-2024-00103", "ALT-2024-00104"],
    detection_hit_ids: [],
    created_at: "2024-11-15T08:23:11Z",
    updated_at: "2024-11-15T09:47:33Z",
  },
  {
    tenant_id: "dev-tenant",
    incident_id: "INC-2024-002",
    correlated_group_id: "grp-002",
    severity: "high",
    status: "ack",
    max_risk_score: 76,
    max_confidence: 0.83,
    mitre_tactic: "Command and Control",
    mitre_technique: "T1071",
    alert_count: 3,
    hit_count: 5,
    assigned_to: "analyst@viola.corp",
    closure_reason: null,
    request_id: null,
    labels: { category: "c2", phase: "beaconing" },
    entity_ids: ["host:laptop-07.corp", "host:proxy-01.corp"],
    alert_ids: ["ALT-2024-00105"],
    detection_hit_ids: [],
    created_at: "2024-11-14T14:05:22Z",
    updated_at: "2024-11-15T07:12:45Z",
  },
  {
    tenant_id: "dev-tenant",
    incident_id: "INC-2024-003",
    correlated_group_id: "grp-003",
    severity: "medium",
    status: "open",
    max_risk_score: 52,
    max_confidence: 0.68,
    mitre_tactic: "Defense Evasion",
    mitre_technique: "T1562",
    alert_count: 2,
    hit_count: 2,
    assigned_to: "soc-tier1@viola.corp",
    closure_reason: null,
    request_id: null,
    labels: { category: "defense-evasion" },
    entity_ids: ["host:server-12.corp"],
    alert_ids: [],
    detection_hit_ids: [],
    created_at: "2024-11-13T22:18:03Z",
    updated_at: "2024-11-14T06:30:15Z",
  },
  {
    tenant_id: "dev-tenant",
    incident_id: "INC-2024-004",
    correlated_group_id: "grp-004",
    severity: "low",
    status: "closed",
    max_risk_score: 18,
    max_confidence: 0.42,
    mitre_tactic: "Discovery",
    mitre_technique: "T1046",
    alert_count: 1,
    hit_count: 1,
    assigned_to: "analyst@viola.corp",
    closure_reason: "Confirmed authorized pen test — false positive",
    request_id: null,
    labels: { category: "network-scan" },
    entity_ids: ["host:dev-laptop-22.corp"],
    alert_ids: [],
    detection_hit_ids: [],
    created_at: "2024-11-12T11:44:55Z",
    updated_at: "2024-11-12T16:20:00Z",
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    tenant_id: "dev-tenant",
    alert_id: "ALT-2024-00101",
    severity: "critical",
    status: "open",
    risk_score: 91,
    confidence: 0.87,
    title: "SMB Lateral Movement — Pass-the-Hash Attempt",
    description: "NTLMv2 pass-the-hash observed from workstation-42.corp targeting dc01.corp.",
    mitre_tactic: "Lateral Movement",
    mitre_technique: "T1550.002",
    labels: { technique: "pth", protocol: "ntlm" },
    entity_ids: ["host:workstation-42.corp", "host:dc01.corp"],
    detection_hit_ids: [],
    assigned_to: null,
    closure_reason: null,
    request_id: null,
    created_at: "2024-11-15T08:23:11Z",
    updated_at: "2024-11-15T08:23:11Z",
  },
  {
    tenant_id: "dev-tenant",
    alert_id: "ALT-2024-00102",
    severity: "critical",
    status: "open",
    risk_score: 95,
    confidence: 0.92,
    title: "Credential Dumping — LSASS Memory Access",
    description: "Process mimikatz.exe accessed lsass.exe memory on workstation-42.corp.",
    mitre_tactic: "Credential Access",
    mitre_technique: "T1003.001",
    labels: { technique: "credential-dump", target: "lsass" },
    entity_ids: ["host:workstation-42.corp"],
    detection_hit_ids: [],
    assigned_to: null,
    closure_reason: null,
    request_id: null,
    created_at: "2024-11-15T08:31:44Z",
    updated_at: "2024-11-15T08:31:44Z",
  },
  {
    tenant_id: "dev-tenant",
    alert_id: "ALT-2024-00103",
    severity: "critical",
    status: "open",
    risk_score: 98,
    confidence: 0.96,
    title: "Ransomware File Extension Mass Rename",
    description: "1247 files renamed to .locked extension on fileserver-03.corp in 45 seconds.",
    mitre_tactic: "Impact",
    mitre_technique: "T1486",
    labels: { technique: "ransomware", target: "fileserver" },
    entity_ids: ["host:fileserver-03.corp"],
    detection_hit_ids: [],
    assigned_to: null,
    closure_reason: null,
    request_id: null,
    created_at: "2024-11-15T09:12:08Z",
    updated_at: "2024-11-15T09:47:33Z",
  },
  {
    tenant_id: "dev-tenant",
    alert_id: "ALT-2024-00104",
    severity: "high",
    status: "open",
    risk_score: 78,
    confidence: 0.74,
    title: "Privilege Escalation — Token Impersonation",
    description: "SeImpersonatePrivilege abused to obtain NT AUTHORITY\\SYSTEM on workstation-42.corp.",
    mitre_tactic: "Privilege Escalation",
    mitre_technique: "T1134.001",
    labels: { technique: "token-impersonation" },
    entity_ids: ["host:workstation-42.corp"],
    detection_hit_ids: [],
    assigned_to: null,
    closure_reason: null,
    request_id: null,
    created_at: "2024-11-15T08:27:55Z",
    updated_at: "2024-11-15T08:27:55Z",
  },
  {
    tenant_id: "dev-tenant",
    alert_id: "ALT-2024-00105",
    severity: "high",
    status: "ack",
    risk_score: 73,
    confidence: 0.81,
    title: "DNS Tunneling — Periodic Beaconing Detected",
    description: "482 DNS queries to c2.evil-domain.xyz with 61s avg interval from laptop-07.corp.",
    mitre_tactic: "Command and Control",
    mitre_technique: "T1071.004",
    labels: { technique: "dns-tunneling", indicator: "beaconing" },
    entity_ids: ["host:laptop-07.corp"],
    detection_hit_ids: [],
    assigned_to: "analyst@viola.corp",
    closure_reason: null,
    request_id: null,
    created_at: "2024-11-14T14:05:22Z",
    updated_at: "2024-11-15T07:12:45Z",
  },
];
